version: "3.1"
services:

  mysql:
    image: mysql:5.7
    container_name: mangas-com-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./data/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mangaslib
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "9092:3306"

  webserver:
    image: nginx:alpine
    container_name: mangas-com-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./logs:/var/log/nginx
    ports:
    - "9090:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: mangas-com-php-fpm
    working_dir: /application
    environment:
      - ENV_APP=local
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  composer:
    image: prooph/composer:7.2
    container_name: sun-composer
    working_dir: /composer
    restart: 'no'
    command: install
    volumes:
      - .:/composer

